// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs ,,const.go

package sys

const (
	FSCTL_LOCK_VOLUME     = 0x90018
	FSCTL_DISMOUNT_VOLUME = 0x90020
	FSCTL_UNLOCK_VOLUME   = 0x9001c
)
